nome = input('digite o nome da aluna:')
idade= int(input('digite a idade da aluna:'))
altura = float(input('digite a altura da aluna: '))
hobbies = input('digite os hobbies da aluna separados por virgula:')
hobbies1 = hobbies.split(',') 
endereco_rua = input ('digite o nome da rua da aluna:')
endereco_numero= input ('digite o numero da casa da aluna:')
endereco_cidade = input ('digite a cidade da aluna:')
endereco = (endereco_rua, endereco_numero, endereco_cidade)
email = input('digite o email da aluna')
telefone = input('digite o telefone da aluna')
contato={'email':email, 'telefone': telefone}

print('\nOla, segue informações sobre a aluna:')
print('nome:', nome)
print('idade:',idade)
print('altura',altura)
print('hobbies:',hobbies)
print('endereco',endereco)
print('contato:',contato)
